# Site settings
title: Shamim's Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Hi! My name is Shamim. I'm a web developer with a post-graduate degree
  in Computer Science. I write web applications mostly using Ruby on Rails
  and modern single-page application javascript frameworks such as Angularjs
  and Backbonejs.
  I love to work with fun and modest, yet knowledgeable people and I strongly
  believe in creating things that make our world a better place for everybody.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sjahandideh.com" # the base hostname & protocol for your site
twitter_username:   shamim_j
github_username:    sjahandideh
linkedln_username:  shamimjahandideh
timezone: Australia/Sydney

# Build settings
markdown: redcarpet
